# This docker image is for execution of the dbt pipelines for
# executing dbt pipelines from a deployment in GKE
#
# BUILD: docker build -t dbt-exec-base .
# EXEC: docker run -v /path/to/dbt-project:/dbt-project -v /path/to/dbt-profiles:/dbt-profiles -v /path/to/service-account.json:/path/in/profiles.yml/service-account.json dbt-test debug

FROM python:3.8.2-slim-buster

# block for adding google package repo for google-cloud-sdk
# ref: https://cloud.google.com/sdk/docs/downloads-apt-get
## NB:: We likely will not need gcloud in deployment if we go cloud build route 
##      + new image/layer for code per job
RUN apt-get update && \
    apt-get install -y apt-transport-https ca-certificates gnupg curl && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - && \
    echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

RUN apt-get update && \
    apt-get install -y git && \
    apt-get -y install google-cloud-sdk tree
COPY . /dbt
RUN cd /dbt && pip install -r editable_requirements.txt
